import { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        shadow: 'var(--shadow)',
        primary: 'var(--primary)',
        secondary: 'var(--secondary)',
        destructive: 'var(--destructive)',
        muted: 'var(--muted)',
        accent: 'var(--accent)',
        popover: 'var(--popover)',
        card: 'var(--card)',
        primaryForeground: 'var(--primary-foreground)',
        secondaryForeground: 'var(--secondary-foreground)',
        mutedForeground: 'var(--muted-foreground)',
        accentForeground: 'var(--accent-foreground)',
        popoverForeground: 'var(--popover-foreground)',
        cardForeground: 'var(--card-foreground)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontSize: {
        // rem sizes
        '.2r': '0.2rem',
        '.4r': '0.4rem',
        '.6r': '0.6rem',
        '.8r': '0.8rem',
        '1r': '1rem',
        '1.2r': '1.2rem',
        '1.4r': '1.4rem',
        '1.6r': '1.6rem',
        '1.8r': '1.8rem',
        '2r': '2rem',
        '2.2r': '2.2rem',
        '2.4r': '2.4rem',
        '2.6r': '2.6rem',
        '2.8r': '2.8rem',
        '3r': '3rem',
        //vertical width
        '.2vw': '.2vw',
        '.4vw': '.4vw',
        '.6vw': '.6vw',
        '.8vw': '.8vw',
        '1vw': '1vw',
        '1.2vw': '1.2vw',
        '1.4vw': '1.4vw',
        '1.6vw': '1.6vw',
        '1.8vw': '1.8vw',
        '2vw': '2vw',
        '2.2vw': '2.2vw',
        '2.4vw': '2.4vw',
        '2.6vw': '2.6vw',
        '2.8vw': '2.8vw',
        '3vw': '3vw',
      },
    },
  },
  plugins: [],
};

export default config;
