"""Allow envelope_id to be nullable in transactions

Revision ID: 2b9086886e46
Revises: 5169f7ba5eba
Create Date: 2024-10-08 13:38:56.124442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9086886e46'
down_revision = '5169f7ba5eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('envelope_id',
                              existing_type=sa.Integer(),
                              nullable=True) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('envelope_id',
                              existing_type=sa.Integer(),
                              nullable=False)

    # ### end Alembic commands ###
